all:
	g++ -O3 -g -std=c++11 -o knn knn.cpp
	g++ -O3 -g -std=c++11 -o test test.cpp
	g++ -O3 -g -std=c++11 -o pca pca.cpp
	g++ -O3 -g -std=c++11 -o pls-da pls-da.cpp
	g++ -O3 -g -std=c++11 -o kCrossVal kCrossVal.cpp
	g++ -O3 -g -std=c++11 -o testCatedra testCatedra.cpp
	g++ -O3 -g -std=c++11 -o main main.cpp


clean:
	rm -f knn test pca pls-da kCrossVal testCatedra main